export const PARKSANDREC = {
  1: {
    1: "Pilot",
    2: "Canvassing",
    3: "The Reporter",
    4: "Boys' Club",
    5: "The Banquet",
    6: "Rock Show",
  },
  2: {
    1: "Pawnee Zoo",
    2: "The Stakeout",
    3: "Beauty Pageant",
    4: "Practice Date",
    5: "Sister City",
    6: "Kaboom",
    7: "Greg Pikitis",
    8: "Ron and Tammy",
    9: "The Camel",
    10: "Hunting Trip",
    11: "Tom's Divorce",
    12: "Christmas Scandal",
    13: "The Set Up",
    14: "Leslie's House",
    15: "Sweetums",
    16: "Galentine's Day",
    17: "Woman of the Year",
    18: "The Possum",
    19: "Park Safety",
    20: "Summer Catalog",
    21: "94 Meetings",
    22: "Telethon",
    23: "The Master Plan",
    24: "Freddy Spaghetti",
  },
  3: {
    1: "Go Big or Go Home",
    2: "Flu Season",
    3: "Time Capsule",
    4: "Ron & Tammy: Part Two",
    5: "Media Blitz",
    6: "Indianapolis",
    7: "Harvest Festival",
    8: "Camping",
    9: "April and Andy's Fancy Party",
    10: "Soulmates",
    11: "Jerry's Painting",
    12: "Eagleton",
    13: "The Fight",
    14: "Road Trip",
    15: "The Bubble",
    16: "Li'l Sebastian",
  },
  4: {
    1: "I'm Leslie Knope",
    2: "Ron and Tammys",
    3: "Born & Raised",
    4: "Pawnee Rangers",
    5: "Meet 'n' Greet",
    6: "End of the World",
    7: "The Treaty",
    8: "Smallest Park",
    9: "The Trial of Leslie Knope",
    10: "Citizen Knope",
    11: "The Comeback Kid",
    12: "Campaign Ad",
    13: "Bowling for Votes",
    14: "Operation Ann",
    15: "Dave Returns",
    16: "Sweet Sixteen",
    17: "Campaign Shake-Up",
    18: "Lucky",
    19: "Live Ammo",
    20: "The Debate",
    21: "Bus Tour",
    22: "Win, Lose, or Draw",
  },
  5: {
    1: "Ms. Knope Goes to Washington",
    2: "Soda Tax",
    3: "How a Bill Becomes a Law",
    4: "Sex Education",
    5: "Halloween Surprise",
    6: "Ben's Parents",
    7: "Leslie vs. April",
    8: "Pawnee Commons",
    9: "Ron and Diane",
    10: "Two Parties",
    11: "Women in Garbage",
    12: "Ann's Decision",
    13: "Emergency Response",
    14: "Leslie and Ben",
    15: "Correspondents' Lunch",
    16: "Bailout",
    17: "Partridge",
    18: "Animal Control",
    19: "Article Two",
    20: "Jerry's Retirement",
    21: "Swing Vote",
    22: "Are You Better Off?",
  },
  6: {
    1: "London",
    2: "The Pawnee-Eagleton Tip Off Classic",
    3: "Doppelgängers",
    4: "Gin It Up!",
    5: "Filibuster",
    6: "Recall Vote",
    7: "Fluoride",
    8: "The Cones of Dunshire",
    9: "Second Chunce",
    10: "New Beginnings",
    11: "Farmers Market",
    12: "Ann and Chris",
    13: "Anniversaries",
    14: "The Wall",
    15: "New Slogan",
    16: "Galentine's Day 2",
    17: "Prom",
    18: "Flu Season 2",
    19: "One in 8,000",
    20: "Moving Up: Part 1",
    21: "Moving Up: Part 2",
  },
  7: {
    1: "2017",
    2: "Ron & Jammy",
    3: "William Henry Harrison",
    4: "Leslie & Ron",
    5: "Gryzzlbox",
    6: "Save JJ's",
    7: "Donna & Joe",
    8: "Ms. Ludgate-Dwyer Goes to Washington",
    9: "Pie-Mary",
    10: "The Johnny Karate Super Awesome Musical Explosion Show",
    11: "Two Funerals",
    12: "One Last Ride: Part 1",
    13: "One Last Ride: Part 2",
  },
  Specials: {
    1: "A Parks and Recreation Special",
  },
};
